### ISSUE TITLE
is custom INDEX supported?

### ISSUE THREAD

**Issue by mihhauk** [vtex/splunkevents-js#32]
I was trying to pass 'index' as specified in docs but it seems not to work.
```
  // Optional. Index created in Splunk. The 'token' option already associates the index info.
  // This option is useful when the token have multiple indexes.
  index: 'YOUR_INDEX',
```

I've started looking why is it not working and realised index property is not used anywhere in config() function https://github.com/vtex/splunkevents-js/blob/cb5f3a49c3c4ae7bac106e5e6909dbc890c2482e/src/index.js#L69

**Comment by Caldas** [comment]
When you send data to Splunk via http (as this library does) the link
between Index and data is the token used when sending data.

So this Index stuff should be removed

Em sex, 12 de jul de 2019 03:03, mihhauk <notifications@github.com>
escreveu:

**Comment by mihhauk** [comment]
Thanks for the answer! I've created a new token with specified index and it works.
