### ISSUE TITLE
How do you use this in a browser?

### ISSUE THREAD

**Issue by lonewarrior556** [vtex/splunkevents-js#33]
It says it's supported by no instructions.

**Comment by salesfelipe** [comment]
Using axios like: 

`const splunkEvents = new SplunkEvents()

splunkEvents.config({
  endpoint: '------',
  token: '-------',
  request: axios,
})

splunkEvents.logEvent`

**Comment by salesfelipe** [comment]
If you have any other doubts you can jus ask here.  :)
